EBBFED/Models/UnionPerson.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBFED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionPerson
    {
        public long ID { get; set; }
        public string ImageUrl { get; set; }
        public string NameA { get; set; }
        public string BriefA { get; set; }
        public string NameE { get; set; }
        public string BriefE { get; set; }
    }
}

EBBFED/Controllers/UnionPersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBBFED.Models;
using EBBFED.Infra;
using static EBBFED.FilterConfig;

namespace EBBFED.Controllers
{
    [AuthorizeUser(Roles = "Admin")]
    public class UnionPersonsController : Controller
    {
        private KoraEntities db = new KoraEntities();

        // GET: UnionPersons
        public ActionResult Index()
        {
            return View(db.UnionPersons.OrderByDescending(r => r.ID).ToList());
        }

        // GET: UnionPersons/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnionPerson unionPerson = db.UnionPersons.Find(id);
            if (unionPerson == null)
            {
                return HttpNotFound();
            }
            return View(unionPerson);
        }

        // GET: UnionPersons/Create
        public ActionResult Create()
        {
            return View(new UnionPersonModel());
        }

        // POST: UnionPersons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UnionPersonModel unionPerson, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var time = DateTimeOffset.Now.ToUnixTimeSeconds();
                string fileName = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                upload.SaveAs(fileName);
                unionPerson.ImageUrl = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                UnionPerson up = new UnionPerson()
                {
                    BriefA=unionPerson.BriefA,
                    BriefE=unionPerson.BriefE,
                    ImageUrl=unionPerson.ImageUrl,
                    NameA=unionPerson.NameA,
                    NameE=unionPerson.NameE
                };
                db.UnionPersons.Add(up);
                db.SaveChanges();

                //********* Start Email Notification *********//
                SendEmail email = new SendEmail();
                string EmailSubject = "عاجل: تغيير جديد فى مجلس الاتحاد المصرى لكره السله ";
                string Category = "مجلس الاتحاد المصرى لكره السله";
                string imgUrl = "http://yaken.cloudapp.net/EBBFEDSiteTest/assets/images/logo-1.png";
                string shortBrief = "قام الاتحاد المصرى لكره السله بتعديل جديد فى مجلس الاتحاد حيث قام بتعيين السيد " + up.NameA;
                string LongDescription = "قام الاتحاد المصرى لكره السله بتعديل جديد فى مجلس الاتحاد حيث قام بتعيين السيد " + up.NameA + "<br>- "+up.BriefA;
                email.Send(EmailSubject, Category,EmailSubject, imgUrl, "", shortBrief, LongDescription);
                //********* End Email Notification *********//

                return RedirectToAction("Index");
            }
            return View(unionPerson);
        }

        // GET: UnionPersons/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnionPerson unionPerson = db.UnionPersons.Find(id);
            if (unionPerson == null)
            {
                return HttpNotFound();
            }
            UnionPersonModel up = new UnionPersonModel()
            {
                ID=unionPerson.ID,
                BriefA = unionPerson.BriefA,
                BriefE = unionPerson.BriefE,
                ImageUrl = unionPerson.ImageUrl,
                NameA = unionPerson.NameA,
                NameE = unionPerson.NameE
            };
            return View(up);
        }

        // POST: UnionPersons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UnionPersonModel unionPerson, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var time = DateTimeOffset.Now.ToUnixTimeSeconds();
                string fileName = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                upload.SaveAs(fileName);
                unionPerson.ImageUrl = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                UnionPerson up = new UnionPerson()
                {
                    ID = unionPerson.ID,
                    BriefA = unionPerson.BriefA,
                    BriefE = unionPerson.BriefE,
                    ImageUrl = unionPerson.ImageUrl,
                    NameA = unionPerson.NameA,
                    NameE = unionPerson.NameE
                };
                db.Entry(up).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(unionPerson);
        }

        // GET: UnionPersons/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnionPerson unionPerson = db.UnionPersons.Find(id);
            if (unionPerson == null)
            {
                return HttpNotFound();
            }
            return View(unionPerson);
        }

        // POST: UnionPersons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            UnionPerson unionPerson = db.UnionPersons.Find(id);
            db.UnionPersons.Remove(unionPerson);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EBBFED/Views/UnionPersons/Create.cshtml
@model EBBFED.Infra.UnionPersonModel

@{
    ViewBag.Title = "Create";
}

<h2>اضافه</h2>


@using (Html.BeginForm("Create", "UnionPersons", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ImportantFigures</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" />
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.NameA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BriefA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.BriefA,2,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BriefA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BriefE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.BriefE,2,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BriefE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("BriefE");
        CKEDITOR.replace("BriefA");

    </script>
}

EBBFED/Views/UnionPersons/Delete.cshtml
@model EBBFED.Models.UnionPerson

@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BriefA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BriefA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BriefE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BriefE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EBBFED/Views/UnionPersons/Details.cshtml
@model EBBFED.Models.UnionPerson

@{
    ViewBag.Title = "Details";
}

<h2>تفاصيل</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            <img class="card-img-top img-fluid" style="height: 250px; width: 250px;" src="~/Content/images/@Model.ImageUrl" alt="Card image cap">
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BriefA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BriefA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BriefE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BriefE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EBBFED/Views/UnionPersons/Edit.cshtml
@model EBBFED.Infra.UnionPersonModel

@{
    ViewBag.Title = "Edit";
}

<h2>تعديل</h2>


@using (Html.BeginForm("Edit", "UnionPersons", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.ImageUrl)

        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.NameE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.BriefA, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.BriefA,2,40, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BriefA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BriefE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.BriefE,2,40, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BriefE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("BriefE");
        CKEDITOR.replace("BriefA");

    </script>
}

EBBFED/Views/UnionPersons/Index.cshtml
@model IEnumerable<EBBFED.Models.UnionPerson>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BriefA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BriefE)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NameA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameE)
        </td>
        <td>
            @Html.Raw(@item.BriefA)
        </td>
        <td>
            @Html.Raw(@item.BriefE)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
        </td>
    </tr>
}

</table>