EBBFED/Models/RulesAndLaw.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBFED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulesAndLaw
    {
        public long ID { get; set; }
        public string NameA { get; set; }
        public string PdfName { get; set; }
        public string NameE { get; set; }
        public string ShortDescriptionA { get; set; }
        public string ShortDescriptionE { get; set; }
    }
}

EBBFED/Controllers/RulesAndLawsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBBFED.Models;
using EBBFED.Infra;

using static EBBFED.FilterConfig;

namespace EBBFED.Controllers
{
    [AuthorizeUser(Roles = "Admin")]
    public class RulesAndLawsController : Controller
    {
        private KoraEntities db = new KoraEntities();

        // GET: RulesAndLaws
        public ActionResult Index()
        {
            return View(db.RulesAndLaws.OrderByDescending(r => r.ID).ToList());
        }

        // GET: RulesAndLaws/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RulesAndLaw rulesAndLaw = db.RulesAndLaws.Find(id);
            if (rulesAndLaw == null)
            {
                return HttpNotFound();
            }
            return View(rulesAndLaw);
        }

        // GET: RulesAndLaws/Create
        public ActionResult Create()
        {
            return View(new RulesAndLawsModel());
        }

        // POST: RulesAndLaws/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RulesAndLawsModel rulesAndLaw, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                string fileName = Path.Combine(Server.MapPath("~/Content/Pdfs"), upload.FileName);
                upload.SaveAs(fileName);
                rulesAndLaw.PdfName = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                RulesAndLaw ral = new RulesAndLaw()
                {
                    NameA = rulesAndLaw.NameA,
                    NameE = rulesAndLaw.NameE,
                    ShortDescriptionA = rulesAndLaw.ShortDescriptionA,
                    ShortDescriptionE = rulesAndLaw.ShortDescriptionE,
                    PdfName = rulesAndLaw.PdfName
                };
                db.RulesAndLaws.Add(ral);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rulesAndLaw);
        }

        // GET: RulesAndLaws/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RulesAndLaw rulesAndLaw = db.RulesAndLaws.Find(id);
            if (rulesAndLaw == null)
            {
                return HttpNotFound();
            }
            RulesAndLawsModel ral = new RulesAndLawsModel()
            {
                ID = rulesAndLaw.ID,
                NameA = rulesAndLaw.NameA,
                NameE = rulesAndLaw.NameE,
                ShortDescriptionA = rulesAndLaw.ShortDescriptionA,
                ShortDescriptionE = rulesAndLaw.ShortDescriptionE,
                PdfName = rulesAndLaw.PdfName
            };
            return View(ral);
        }

        // POST: RulesAndLaws/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RulesAndLawsModel rulesAndLaw, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                string fileName = Path.Combine(Server.MapPath("~/Content/Pdfs"), upload.FileName);
                upload.SaveAs(fileName);
                rulesAndLaw.PdfName = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                RulesAndLaw ral = new RulesAndLaw()
                {
                    ID = rulesAndLaw.ID,
                    NameA = rulesAndLaw.NameA,
                    NameE = rulesAndLaw.NameE,
                    ShortDescriptionA = rulesAndLaw.ShortDescriptionA,
                    ShortDescriptionE = rulesAndLaw.ShortDescriptionE,
                    PdfName = rulesAndLaw.PdfName
                };
                db.Entry(ral).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rulesAndLaw);
        }

        // GET: RulesAndLaws/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RulesAndLaw rulesAndLaw = db.RulesAndLaws.Find(id);
            if (rulesAndLaw == null)
            {
                return HttpNotFound();
            }
            return View(rulesAndLaw);
        }

        // POST: RulesAndLaws/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            RulesAndLaw rulesAndLaw = db.RulesAndLaws.Find(id);
            db.RulesAndLaws.Remove(rulesAndLaw);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EBBFED/Views/RulesAndLaws/Create.cshtml
@model EBBFED.Infra.RulesAndLawsModel

@{
    ViewBag.Title = "Create";
}

<h2>اضافه</h2>


@using (Html.BeginForm("Create", "RulesAndLaws", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.NameE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescriptionA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ShortDescriptionA, 2,40,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescriptionA, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescriptionE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ShortDescriptionE,2 ,40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescriptionE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("ShortDescriptionE");
        CKEDITOR.replace("ShortDescriptionA");

    </script>
}

EBBFED/Views/RulesAndLaws/Delete.cshtml
@model EBBFED.Models.RulesAndLaw

@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescriptionA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescriptionA)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescriptionE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescriptionE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PdfName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PdfName)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EBBFED/Views/RulesAndLaws/Details.cshtml
@model EBBFED.Models.RulesAndLaw

@{
    ViewBag.Title = "Details";
}

<h2>تفاصيل</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescriptionA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescriptionA)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescriptionE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescriptionE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PdfName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PdfName)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EBBFED/Views/RulesAndLaws/Edit.cshtml
@model EBBFED.Infra.RulesAndLawsModel

@{
    ViewBag.Title = "Edit";
}

<h2>تعديل</h2>


@using (Html.BeginForm("Edit", "RulesAndLaws", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.PdfName)
        <div class="form-group">
            @Html.LabelFor(model => model.NameA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescriptionA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ShortDescriptionA, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescriptionA, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescriptionE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ShortDescriptionE, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescriptionE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("ShortDescriptionE");
        CKEDITOR.replace("ShortDescriptionA");

    </script>
}

EBBFED/Views/RulesAndLaws/Index.cshtml
@model IEnumerable<EBBFED.Models.RulesAndLaw>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameE)
        </th>

        <td>
            @Html.DisplayNameFor(model => model.ShortDescriptionA)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.ShortDescriptionE)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.PdfName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.NameA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameE)
            </td>
            <td>
                @Html.Raw(@item.ShortDescriptionA)
            </td>
            <td>
                @Html.Raw(@item.ShortDescriptionE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PdfName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>