EBBFED/Models/UnoinCommitte.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBFED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnoinCommitte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnoinCommitte()
        {
            this.ComitteMembers = new HashSet<ComitteMember>();
        }
    
        public long ID { get; set; }
        public string ImageUrl { get; set; }
        public string NameA { get; set; }
        public string NameE { get; set; }
        public string ObjectivesA { get; set; }
        public string ObjectivesE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComitteMember> ComitteMembers { get; set; }
    }
}

EBBFED/Controllers/UnoinCommittesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBBFED.Models;
using EBBFED.Infra;
using static EBBFED.FilterConfig;

namespace EBBFED.Controllers
{
    [AuthorizeUser(Roles = "Admin")]
    public class UnoinCommittesController : Controller
    {
        private KoraEntities db = new KoraEntities();

        // GET: UnoinCommittes
        public ActionResult Index()
        {
            return View(db.UnoinCommittes.OrderByDescending(r => r.ID).ToList());
        }

        // GET: UnoinCommittes/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnoinCommitte unoinCommitte = db.UnoinCommittes.Find(id);
            if (unoinCommitte == null)
            {
                return HttpNotFound();
            }
            return View(unoinCommitte);
        }

        // GET: UnoinCommittes/Create
        public ActionResult Create()
        {
            return View(new UnoinCommitteModel());
        }

        // POST: UnoinCommittes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UnoinCommitteModel unoinCommitte, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var time = DateTimeOffset.Now.ToUnixTimeSeconds();
                string fileName = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                upload.SaveAs(fileName);
                unoinCommitte.ImageUrl = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                UnoinCommitte un = new UnoinCommitte()
                {
                    ImageUrl = unoinCommitte.ImageUrl,
                    NameA = unoinCommitte.NameA,
                    NameE = unoinCommitte.NameE,
                    ObjectivesA = unoinCommitte.ObjectivesA,
                    ObjectivesE = unoinCommitte.ObjectivesE,
                };
                db.UnoinCommittes.Add(un);
                for (int i = 0; i < unoinCommitte.MemberNameA.Count; i++)
                {
                    if (unoinCommitte.MemberNameA[i].Length == 0 || unoinCommitte.MemberNameE[i].Length == 0)
                        continue;
                    ComitteMember cm = new ComitteMember()
                    {
                        NameA = unoinCommitte.MemberNameA[i],
                        NameE = unoinCommitte.MemberNameE[i],
                        CommitteID = un.ID
                    };
                    db.ComitteMembers.Add(cm);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(unoinCommitte);
        }

        // GET: UnoinCommittes/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnoinCommitte unoinCommitte = db.UnoinCommittes.Find(id);
            if (unoinCommitte == null)
            {
                return HttpNotFound();
            }
            List<string> MemberNameAs= db.ComitteMembers.Where(t => t.CommitteID == id).Select(t => t.NameA).ToList();
            List<string> MemberNameEs = db.ComitteMembers.Where(t => t.CommitteID == id).Select(t => t.NameE).ToList();
            UnoinCommitteModel un = new UnoinCommitteModel()
            {
                ID = unoinCommitte.ID,
                ImageUrl = unoinCommitte.ImageUrl,
                NameA = unoinCommitte.NameA,
                NameE = unoinCommitte.NameE,
                ObjectivesA = unoinCommitte.ObjectivesA,
                ObjectivesE = unoinCommitte.ObjectivesE,
                MemberNameA= MemberNameAs,
                MemberNameE= MemberNameEs,
            };
            return View(un);
        }

        // POST: UnoinCommittes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UnoinCommitteModel unoinCommitte, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var time = DateTimeOffset.Now.ToUnixTimeSeconds();
                string fileName = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                upload.SaveAs(fileName);
                unoinCommitte.ImageUrl = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                UnoinCommitte un = new UnoinCommitte()
                {
                    ID = unoinCommitte.ID,
                    ImageUrl = unoinCommitte.ImageUrl,
                    NameA = unoinCommitte.NameA,
                    NameE = unoinCommitte.NameE,
                    ObjectivesA = unoinCommitte.ObjectivesA,
                    ObjectivesE = unoinCommitte.ObjectivesE,
                };
                List<long> MemberIDs = db.ComitteMembers.Where(t => t.CommitteID == unoinCommitte.ID).Select(t => t.ID).ToList();
                for (int i = 0; i < unoinCommitte.MemberNameA.Count; i++)
                {
                    var member = db.ComitteMembers.Find(MemberIDs[i]);
                    member.NameA = unoinCommitte.MemberNameA[i];
                    member.NameE = unoinCommitte.MemberNameE[i];
                    db.Entry(member).State = EntityState.Modified;
                }
                for (int i = 0; i < unoinCommitte.MemberNameAe.Count; i++)
                {
                    if (unoinCommitte.MemberNameAe[i].Length == 0 || unoinCommitte.MemberNameEe[i].Length == 0)
                        continue;
                    ComitteMember cm = new ComitteMember()
                    {
                        NameA = unoinCommitte.MemberNameAe[i],
                        NameE = unoinCommitte.MemberNameEe[i],
                        CommitteID = un.ID
                    };
                    db.ComitteMembers.Add(cm);
                }
                db.Entry(un).State = EntityState.Modified;
                db.SaveChanges();
                /////////////////////////////
                string mailSubject = "تعديل فى مجلس الاتحاد";
                string mailBody = $"<h2>{un.NameA}</h2><br /><h3>{un.ObjectivesA}</h3>";
                UserNotificationModel.SendEmail(mailSubject, mailBody);
                return RedirectToAction("Index");
            }
            return View(unoinCommitte);
        }

        // GET: UnoinCommittes/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnoinCommitte unoinCommitte = db.UnoinCommittes.Find(id);
            if (unoinCommitte == null)
            {
                return HttpNotFound();
            }
            return View(unoinCommitte);
        }

        // POST: UnoinCommittes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            UnoinCommitte unoinCommitte = db.UnoinCommittes.Find(id);
            db.UnoinCommittes.Remove(unoinCommitte);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EBBFED/Views/UnoinCommittes/Create.cshtml
@model EBBFED.Infra.UnoinCommitteModel

@{
    ViewBag.Title = "Create";
}

<h2>اضافه</h2>


@using (Html.BeginForm("Create", "UnoinCommittes", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameA, "الاسم عربى", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameE, "الاسم انجليزى", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ObjectivesA, " الاهداف عربى", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ObjectivesA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ObjectivesA, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ObjectivesE, "الاهداف انجليزى", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ObjectivesE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ObjectivesE, "", new { @class = "text-danger" })
            </div>
        </div>


        <div id="member">
            <div id="add">
                <div class="row">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.MemberNameA, "اسم العضو عربى", htmlAttributes: new { @class = "control-label col-md-2" })
                        <br />
                        <input type="text" name="MemberNameAe[]" class="form-control" />
                    </div>

                    <div class="col-md-4">
                        @Html.LabelFor(model => model.MemberNameE, "اسم العضو انجليزى", htmlAttributes: new { @class = "control-label col-md-2" })
                        <br />
                        <input type="text" name="MemberNameEe[]" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
        <br />
        <input type="button" id="addMember" class="btn btn-primary" value="Add Member" />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#addMember").click(function () {
            var row = $('#add').html();
            $("#member").append(row);
        });
    </script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("ObjectivesA");
        CKEDITOR.replace("ObjectivesE");

    </script>
}

EBBFED/Views/UnoinCommittes/Delete.cshtml
@model EBBFED.Models.UnoinCommitte

@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EBBFED/Views/UnoinCommittes/Details.cshtml
@model EBBFED.Models.UnoinCommitte

@{
    ViewBag.Title = "Details";
}

<h2>تفاصبل</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            <img class="card-img-top img-fluid" style="height: 250px; width: 250px;" src="~/Content/images/@Model.ImageUrl" alt="Card image cap">

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EBBFED/Views/UnoinCommittes/Edit.cshtml
@model EBBFED.Infra.UnoinCommitteModel

@{
    ViewBag.Title = "Edit";
}

<h2>تعديل</h2>


@using (Html.BeginForm("Edit", "UnoinCommittes", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.ImageUrl)

    <div class="form-group">
        @Html.Label("الصوره", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Photo" name="upload" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NameA,"الاسم عربى", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NameE, "الاسم انجليزى",htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ObjectivesA," الاهداف عربى", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ObjectivesA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ObjectivesA, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ObjectivesE,"الاهداف انجليزى", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ObjectivesE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ObjectivesE, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.MemberNameA,"الاسم العضو عربى" ,htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.MemberNameA, new { htmlAttributes = new { @class = "form-control", @name = "MemberNameA[]" } })
                @Html.ValidationMessageFor(model => model.MemberNameA, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.MemberNameE,"اسم العضو انجليزى", htmlAttributes: new { @class = "control-label col-md-2" })
                <br />
                @Html.EditorFor(model => model.MemberNameE, new { htmlAttributes = new { @class = "form-control", @name = "MemberNameE[]" } })
                @Html.ValidationMessageFor(model => model.MemberNameE, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div id="member">
        <div id="add">
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.MemberNameA,"اسم العضو عربى", htmlAttributes: new { @class = "control-label col-md-2" })
                    <br />
                    <input type="text" name="MemberNameAe[]" class="form-control" />
                </div>

                <div class="col-md-4">
                    @Html.LabelFor(model => model.MemberNameE,"اسم العضو انجليزى", htmlAttributes: new { @class = "control-label col-md-2" })
                    <br />
                    <input type="text" name="MemberNameEe[]" class="form-control" />
                </div>
            </div>
        </div>
    </div>
    <br />
    <input type="button" id="addMember" class="btn btn-primary" value="Add Member" />
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#addMember").click(function () {
            var row = $('#add').html();
            $("#member").append(row);
        });
    </script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("ObjectivesA");
        CKEDITOR.replace("ObjectivesE");

    </script>
}

EBBFED/Views/UnoinCommittes/Index.cshtml
@model IEnumerable<EBBFED.Models.UnoinCommitte>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameE)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NameA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameE)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>