EBBFED/Models/Club.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBFED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.Coahes = new HashSet<Coahe>();
            this.GalleryClubs = new HashSet<GalleryClub>();
            this.NewsClubs = new HashSet<NewsClub>();
            this.PlayerClubs = new HashSet<PlayerClub>();
            this.Players = new HashSet<Player>();
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.Statisticians = new HashSet<Statistician>();
        }
    
        public long ID { get; set; }
        public string NameE { get; set; }
        public string NameA { get; set; }
        public long DivisionID { get; set; }
        public string Logo { get; set; }
        public Nullable<int> EstablishedYear { get; set; }
        public string TitlesWon { get; set; }
        public string DescriptionA { get; set; }
        public string DescriptionE { get; set; }
        public Nullable<int> AreaID { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coahe> Coahes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GalleryClub> GalleryClubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsClub> NewsClubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerClub> PlayerClubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistician> Statisticians { get; set; }
    }
}

EBBFED/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBBFED.Models;
using EBBFED.Infra;
using static EBBFED.FilterConfig;

namespace EBBFED.Controllers
{
    [AuthorizeUser(Roles = "Admin")]
    public class ClubsController : Controller
    {
        private KoraEntities db = new KoraEntities();

        // GET: Clubs
        public ActionResult Index()
        {
            var clubs = db.Clubs.Include(c => c.Division);
            return View(clubs.OrderByDescending(r => r.ID).ToList());
        }

        // GET: Clubs/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // GET: Clubs/Create
        public ActionResult Create()
        {
            ViewBag.DivisionID = new SelectList(db.Divisions, "ID", "NameA");
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "NameA");
            return View(new ClubsModel());
        }

        // POST: Clubs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClubsModel club, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var time = DateTimeOffset.Now.ToUnixTimeSeconds();
                string fileName = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                upload.SaveAs(fileName);
                club.Logo = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                Club clubs = new Club()
                {
                    Logo=club.Logo,
                    NameA=club.NameA,
                    NameE=club.NameE,
                    DescriptionA=club.DescriptionA,
                    DescriptionE=club.DescriptionE,
                    DivisionID=club.DivisionID,
                    AreaID=(int)club.AreaID,
                    EstablishedYear=club.EstablishedYear,
                    TitlesWon=club.TitlesWon
                };
                db.Clubs.Add(clubs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DivisionID = new SelectList(db.Divisions, "ID", "NameA", club.DivisionID);
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "NameA");

            return View(club);
        }

        // GET: Clubs/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            ViewBag.DivisionID = new SelectList(db.Divisions, "ID", "NameA", club.DivisionID);
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "NameA", club.AreaID ?? 0);

            ClubsModel clubs = new ClubsModel()
            {
                Logo = club.Logo,
                NameA = club.NameA,
                NameE = club.NameE,
                DescriptionA = club.DescriptionA,
                DescriptionE = club.DescriptionE,
                DivisionID = club.DivisionID,
                AreaID = club.AreaID ?? 0,
                EstablishedYear = club.EstablishedYear??0,
                TitlesWon = club.TitlesWon
            };
            return View(clubs);
        }

        // POST: Clubs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClubsModel club, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var time = DateTimeOffset.Now.ToUnixTimeSeconds();
                string fileName = Path.Combine(Server.MapPath("~/Content/Images"), upload.FileName);
                upload.SaveAs(fileName);
                club.Logo = upload.FileName;
            }
            if (ModelState.IsValid)
            {
                Club clubs = new Club()
                {
                    ID=club.ID,
                    Logo = club.Logo,
                    NameA = club.NameA,
                    NameE = club.NameE,
                    DescriptionA = club.DescriptionA,
                    DescriptionE = club.DescriptionE,
                    DivisionID = club.DivisionID,
                    AreaID = (int)club.AreaID,
                    EstablishedYear = club.EstablishedYear,
                    TitlesWon = club.TitlesWon
                };
                db.Entry(clubs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DivisionID = new SelectList(db.Divisions, "ID", "NameA", club.DivisionID);
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "NameA", club.AreaID);
            return View(club);
        }

        // GET: Clubs/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        // POST: Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Club club = db.Clubs.Find(id);
            db.Clubs.Remove(club);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EBBFED/Views/Clubs/Create.cshtml
@model EBBFED.Infra.ClubsModel

@{
    ViewBag.Title = "Create";
}

<h2>اضافه</h2>


@using (Html.BeginForm("Create", "Clubs", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DivisionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DivisionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DivisionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreaID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AreaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AreaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstablishedYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstablishedYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstablishedYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TitlesWon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TitlesWon, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitlesWon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.DescriptionA, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.DescriptionE, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("DescriptionA");
        CKEDITOR.replace("DescriptionE");
        CKEDITOR.replace("TitlesWon");

    </script>
}

EBBFED/Views/Clubs/Delete.cshtml
@model EBBFED.Models.Club

@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstablishedYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstablishedYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitlesWon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitlesWon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Division.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Division.NameA)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EBBFED/Views/Clubs/Details.cshtml
@model EBBFED.Models.Club

@{
    ViewBag.Title = "Details";
}

<h2>تفاصيل</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            <img class="card-img-top img-fluid" style="height: 250px; width: 250px;" src="~/Content/images/@Model.Logo" alt="Card image cap">
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstablishedYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstablishedYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TitlesWon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitlesWon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Division.NameA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Division.NameA)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EBBFED/Views/Clubs/Edit.cshtml
@model EBBFED.Infra.ClubsModel

@{
    ViewBag.Title = "Edit";
}

<h2>تعديل</h2>


@using (Html.BeginForm("Edit", "Clubs", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Logo)

        <div class="form-group">
            @Html.LabelFor(model => model.NameE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DivisionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DivisionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DivisionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreaID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AreaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AreaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("الصوره", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstablishedYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstablishedYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstablishedYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TitlesWon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TitlesWon, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitlesWon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.DescriptionA, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.DescriptionE, 2, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.env.isCompatible = true;
        CKEDITOR.replace("DescriptionA");
        CKEDITOR.replace("DescriptionE");
        CKEDITOR.replace("TitlesWon");
    </script>
}

EBBFED/Views/Clubs/Index.cshtml
@model IEnumerable<EBBFED.Models.Club>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstablishedYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TitlesWon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Division)
        </th>
        <th>
            Area
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstablishedYear)
            </td>
            <td>
                @Html.Raw(@item.TitlesWon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Division.NameA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area.NameE) | @Html.DisplayFor(modelItem => item.Area.NameA)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>